[project]
name = "llm-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Farana", email = "farana.alibhai@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic<1.0",
    "openrouter>=1.1.133",
    "python-dotenv>=1.2.3",
]

[project.scripts]
llm-app = "llm_app:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
